import "./globals.css";
import Nav from "@/components/nav/nav";
import { Cursor } from "@/utils/cursor";

export const metadata = {
  title: "ericyue",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Cursor />
        {children}
        <Nav />
      </body>
    </html>
  );
}
