import "./globals.css";
import Footer from "@/components/footer/footer";
import { Cursor } from "@/utils/cursor";

export const metadata = {
  title: "ericyue",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Cursor />
        {children}
        <Footer />
      </body>
    </html>
  );
}
